### ISSUE TITLE
It's necessary to provide reset password api in cli

### ISSUE THREAD

**Issue by Yeuoly** [zilliztech/milvus_cli#28]
As usually, we never want to change password by write some python codes and execute it, and authorization is very important in current world, why not just provide it in cli? or maybe I can provide a PR to milvus_cli project to implement this feature

**Comment by Yeuoly** [comment]
@shanghaikid are those in list?

**Comment by shanghaikid** [comment]
> @shanghaikid are those in list?

Any contribution is welcome.   We are about to update this cli to support the latest milvus features in two or three weeks.

**Comment by Yeuoly** [comment]
Pull Request has been sent, thank you for your comment.
