### ISSUE TITLE
[Bug] Command "show loading_progress" is unusable

### ISSUE THREAD

**Issue by WuYiFan0108** [zilliztech/milvus_cli#32]
Command "show loading_progress" errors anyway no matter how I use this command:
![image](https://github.com/zilliztech/milvus_cli/assets/139840531/3d4a3114-e6cb-4a00-9d44-8f8068843af8)
![image](https://github.com/zilliztech/milvus_cli/assets/139840531/f1d0a056-e4c5-49c9-98ce-e70f87a0af99)
After some look up, I found that milvus_cli passes the partition parameter of tuple type to pymilvus, but pymilvus only accepts the partition parameter of list type, resulting in the above error.
I think there are two solutions to this issuse:

1. Implement a callback function in "show loading_progress" which transform the partition parameter of tuple type to list type.
2. Modify pymilvus to make pymilvus support partition_arrary parameter input of tuple type.

I personally prefer solution 1 because it this has the least impact on the whole Milvus project, and I've already implemented this.
Please let me know what you think.

**Comment by nameczz** [comment]
Will have a new release to support new Milvus and Pymilvus asps. Also will fix this issue.

**Comment by WuYiFan0108** [comment]
> Will have a new release to support new Milvus and Pymilvus asps. Also will fix this issue.

So, I guess there is no need to open a new pull request?

**Comment by nameczz** [comment]
@WuYiFan0108 Yes, we will refactor the codes by new pymilvus. Thanks for your suggestions. Any update will let you know!

**Comment by nameczz** [comment]
@WuYiFan0108 please have a try with new release v0.4.0. Thanks

**Comment by WuYiFan0108** [comment]
It's working well. Nice job on the refactoring!👍
