### ISSUE TITLE
安装milvus_cli，就会自动卸载之前安装的2.2.9版的pymilvus，安装低版本pymilvus-2.2.1

### ISSUE THREAD

**Issue by Youfenghao** [zilliztech/milvus_cli#39]
安装milvus_cli，就会自动卸载之前安装的2.2.9版的pymilvus， 给我安装一个低版本的pymilvus-2.2.1, 导致代码在导入数据时报找不到from milvus import db, 需要重新安装pymilvus?, 希望zilliz工程师能尽快修复版本库包问题

**Comment by nameczz** [comment]
@Youfenghao  Please have a a try with new release v0.4.0. 
We use the latest pymilvus==v2.3.0 in new release. Need to install pymilvus again if you need other version.
