### ISSUE TITLE
[BUG] Error: No such command 'describe'

### ISSUE THREAD

**Issue by Pickupppp** [zilliztech/milvus_cli#55]
我的版本如下：
- python 3.8.17
- pymilvus 2.3.0
- milvus_cli 0.4.0
当我使用 milvus_cli 连接到 milvus 后，执行 `describe collection -c test_collection` ，命令行报错 `Error: No such command 'describe'.`

**Comment by nameczz** [comment]
@Pickupppp  we change describe to show in v0.4.0
Like show collection -c (text)
