### ISSUE TITLE
how to connect db use milvus_cli0.4.0

### ISSUE THREAD

**Issue by Jz-Lin** [zilliztech/milvus_cli#59]
connect db error use milvus_cli0.4.0

 connect -uri 192.168.xx.xx:19530 -t root:xxxx
message=I1legal uri: [192.168.xx.xx:19530]，expected form "http[s]://[user :password@Jexample.c
connect to MiTvus error!<ConnectionConfigException: (code=1,
:12345>

**Comment by nameczz** [comment]
@Jz-Lin  https://milvus.io/docs/cli_commands.md#connect 
try to use: connect -uri http://192.168.xx.xx:19530 -t root:xxxx
