### ISSUE TITLE
milvus_cli show collection does not support json schema

### ISSUE THREAD

**Issue by younger027** [zilliztech/milvus_cli#60]
![image](https://github.com/zilliztech/milvus_cli/assets/14865571/98366c9f-9061-4a58-9382-84b629b56e5f)
as picture show. when i run 'show collection -c $collection_name'.i got different response. question collection schema not have json filed. openai_amc_question have json field like 'FieldSchema(name='question_meta', dtype=DataType.JSON),'

please tell me what happened?

**Comment by younger027** [comment]
Milvus cli version: 0.4.0
Pymilvus version: 2.3.0

**Comment by nameczz** [comment]
@younger027  sure, will update soon

**Comment by nameczz** [comment]
@younger027 please try 0.4.1
