### ISSUE TITLE
Some commands have been invalid but still appears in the doc.

### ISSUE THREAD

**Issue by Phobia-Cosmos** [zilliztech/milvus_cli#68]
I've learned from the [Get started with Milvus_CLI](https://milvus.io/blog/2021-12-31-get-started-with-milvus-cli.md) and the [Milvus_CLI Command Reference](https://milvus.io/docs/v2.0.x/cli_commands.md#version), but the command like the import has been removed it seems and still in the docs.
<img width="619" alt="image" src="https://github.com/zilliztech/milvus_cli/assets/107133423/4ca6cbeb-af36-4078-80f0-79e18ea08e66">
<img width="841" alt="image" src="https://github.com/zilliztech/milvus_cli/assets/107133423/535e4169-8f84-4a38-8258-ff2f00d01ba3">

**Comment by nameczz** [comment]
@Phobia-Cosmos my bad, will fix in next release.

**Comment by nameczz** [comment]
@Phobia-Cosmos already update v2.3.x docs

**Comment by vsian** [comment]
There is still an import in the document in 2.3.x and 2.4.x.
