### ISSUE TITLE
The container version is 0.3.0 created with docker run-it zilliz/milvus_cli:latest

### ISSUE THREAD

**Issue by yuan8180** [zilliztech/milvus_cli#84]
after
docker run-it zilliz/milvus_cli:latest
View the version and find that the version is 0.3.0,but the latest version is 1.0.0
What do I do if I want to install version 0.4.2

**Comment by nameczz** [comment]
@yuan8180 i fixed docker publish file. And we have v1.0.0 and latest (v1.0.0) in docker hub.
But we can't publish the older version ,sorry for that. 
so you can only get v1.0.0 milvus_cli in docker before new releases.
